name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Discover and Test All Projects
        run: |
          for dir in $(find . -maxdepth 1 -type d -name "num*"); do
            echo "Processing $dir"
            (cd $dir && cargo build --verbose && cargo test --verbose)
          done
